# Generated by Django 5.0.4 on 2024-05-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
